package com.mosoft.optionfusion.util;

import java.text.DecimalFormat;

import lecho.lib.hellocharts.formatter.AxisValueFormatter;
import lecho.lib.hellocharts.model.AxisValue;

public class PercentAxisValueFormatter implements AxisValueFormatter {

    DecimalFormat decimalFormat = new DecimalFormat("@%");
    DecimalFormat decimalFormatBig = new DecimalFormat("@E0x");

    @Override
    public int formatValueForManualAxis(char[] formattedValue, AxisValue axisValue) {
        return formatValueForAutoGeneratedAxis(formattedValue, axisValue.getValue(), 2);
    }

    @Override
    public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits) {
        String label = value > 10
                ? decimalFormatBig.format(value)
                : decimalFormat.format(value);
        System.arraycopy(label.toCharArray(), 0, formattedValue, formattedValue.length - label.length(), label.length());
        return label.length();
    }

}
